"""add_training_summaries_table

Revision ID: 6a5faef33171
Revises: b5e8d2f3017a
Create Date: 2026-04-27 09:50:47.291881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6a5faef33171'
down_revision: Union[str, Sequence[str], None] = 'b5e8d2f3017a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_summaries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('ai_usage_log_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ai_usage_log_id'], ['ai_usage_logs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'course_id', name='uq_student_course_summary')
    )
    op.create_index(op.f('ix_training_summaries_course_id'), 'training_summaries', ['course_id'], unique=False)
    op.create_index(op.f('ix_training_summaries_student_id'), 'training_summaries', ['student_id'], unique=False)
    op.alter_column('prompt_templates', 'variables',
               existing_type=mysql.TEXT(),
               comment='JSON array of variable names',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prompt_templates', 'variables',
               existing_type=mysql.TEXT(),
               comment=None,
               existing_comment='JSON array of variable names',
               existing_nullable=False)
    op.drop_index(op.f('ix_training_summaries_student_id'), table_name='training_summaries')
    op.drop_index(op.f('ix_training_summaries_course_id'), table_name='training_summaries')
    op.drop_table('training_summaries')
    # ### end Alembic commands ###
