"""add venues and equipment tables

Revision ID: eaa79625a9ad
Revises: 59e37cad18dd
Create Date: 2026-04-27 18:09:59.215916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eaa79625a9ad'
down_revision: Union[str, Sequence[str], None] = '59e37cad18dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('venues',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('active', 'inactive', 'maintenance')", name='chk_venue_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_venues_external_id', 'venues', ['external_id'], unique=False)
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('active', 'inactive', 'maintenance')", name='chk_equipment_status'),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_equipment_external_id', 'equipment', ['external_id'], unique=False)
    op.create_index('ix_equipment_serial_number', 'equipment', ['serial_number'], unique=True)
    op.create_index(op.f('ix_equipment_venue_id'), 'equipment', ['venue_id'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('booked_by', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('client_ref', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('approved', 'cancelled')", name='chk_booking_status'),
    sa.ForeignKeyConstraint(['booked_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bookings_booked_by', 'bookings', ['booked_by'], unique=False)
    op.create_index(op.f('ix_bookings_class_id'), 'bookings', ['class_id'], unique=False)
    op.create_index('ix_bookings_client_ref', 'bookings', ['client_ref'], unique=True)
    op.create_index(op.f('ix_bookings_course_id'), 'bookings', ['course_id'], unique=False)
    op.create_index('ix_bookings_status', 'bookings', ['status'], unique=False)
    op.create_index(op.f('ix_bookings_task_id'), 'bookings', ['task_id'], unique=False)
    op.create_index(op.f('ix_bookings_venue_id'), 'bookings', ['venue_id'], unique=False)
    op.create_index('ix_bookings_venue_time', 'bookings', ['venue_id', 'start_time', 'end_time'], unique=False)
    op.create_table('booking_equipment',
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('booking_id', 'equipment_id')
    )
    op.create_index('ix_booking_equipment_equip', 'booking_equipment', ['equipment_id', 'booking_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Drop tables before indexes (MySQL requires FK constraints to exist for indexed columns)
    op.drop_table('booking_equipment')
    op.drop_index('ix_bookings_client_ref', table_name='bookings')
    op.drop_index('ix_bookings_venue_time', table_name='bookings')
    op.drop_table('bookings')
    op.drop_index('ix_equipment_serial_number', table_name='equipment')
    op.drop_index('ix_equipment_external_id', table_name='equipment')
    op.drop_table('equipment')
    op.drop_index('ix_venues_external_id', table_name='venues')
    op.drop_table('venues')
